# Copyright (c) 2024 Christopher Wolf. All rights reserved.
# This software is proprietary and confidential.
# Unauthorized copying of this file, via any medium, is strictly prohibited.

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  # Optional: Auto-create topics
    volumes:
      - ./create-topics.sh:/create-topics.sh  # Copy the script
    command: ["/bin/bash", "-c", "/create-topics.sh && sleep infinity"]
    depends_on:
      - zookeeper



# how to manually create topics with docker
# docker exec -it kafka kafka-topics.sh --create \
#  --topic transactions --bootstrap-server localhost:9092 \
#  --replication-factor 1 --partitions 1